from __future__ import annotations

import subprocess
from pathlib import Path

import pytest

from gdb_mcp.gdb_manager import GdbSessionManager


@pytest.fixture()
def compiled_crash(tmp_path: Path) -> Path:
    repo_root = Path(__file__).resolve().parents[1]
    source = repo_root / "examples" / "crash.c"
    output = tmp_path / "crash_dbg"

    subprocess.run(
        ["gcc", "-g", "-O0", str(source), "-o", str(output)],
        check=True,
        capture_output=True,
        text=True,
    )
    return output


@pytest.mark.integration
def test_gdb_session_debug_workflow(compiled_crash: Path) -> None:
    manager = GdbSessionManager()
    started = manager.start_session(working_dir=str(compiled_crash.parent))
    session_id = started["session_id"]

    try:
        manager.command(session_id, "set pagination off")
        manager.set_program_args(session_id, ["15"])

        load_result = manager.load_program(session_id, str(compiled_crash), None)
        assert load_result["target"] == str(compiled_crash)
        assert "Reading symbols" in load_result["load_output"]

        bp_result = manager.set_breakpoint(session_id, "main")
        assert "Breakpoint" in bp_result["breakpoint_output"]
        bp_list = manager.list_breakpoints(session_id)
        assert "main" in bp_list

        run_output = manager.command(session_id, "run")
        assert "Breakpoint" in run_output

        threads_output = manager.info_threads(session_id)
        assert "Thread" in threads_output

        print_output = manager.print_expression(session_id, "number")
        assert "$" in print_output

        manager.set_breakpoint(session_id, "function_that_crashes")
        manager.continue_execution(session_id)
        crash_report = manager.collect_crash_report(session_id, backtrace_limit=6)
        assert "backtrace" in crash_report
        assert "#0" in crash_report["backtrace"]

        frame_output = manager.select_frame(session_id, 1)
        assert "#1" in frame_output

        bt_output = manager.backtrace(session_id, limit=5)
        assert "#0" in bt_output
    finally:
        manager.terminate_all()


@pytest.mark.integration
def test_load_core_with_generated_core_file(compiled_crash: Path, tmp_path: Path) -> None:
    manager = GdbSessionManager()
    core_path = tmp_path / "generated_core"

    start_one = manager.start_session(working_dir=str(compiled_crash.parent))
    sid_one = start_one["session_id"]
    try:
        manager.load_program(sid_one, str(compiled_crash), ["15"])
        manager.set_breakpoint(sid_one, "function_that_crashes")
        run_out = manager.command(sid_one, "run")
        assert "Breakpoint" in run_out

        manager.continue_execution(sid_one)
        dump_out = manager.command(sid_one, f"generate-core-file {core_path}")
        assert "Saved corefile" in dump_out
    finally:
        manager.terminate_session(sid_one)

    start_two = manager.start_session(working_dir=str(compiled_crash.parent))
    sid_two = start_two["session_id"]
    try:
        loaded = manager.load_core(sid_two, str(compiled_crash), str(core_path))
        assert "Core was generated by" in loaded["core_output"]
        assert "#0" in loaded["backtrace_output"]
    finally:
        manager.terminate_all()
